// Code generated by Kitex v0.13.0. DO NOT EDIT.

package kwservice

import (
	"context"
	"errors"
	kw "github.com/ChangKaiChen/lx-music-api-server/kitex_gen/kw"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"KwMusicUrl": kitex.NewMethodInfo(
		kwMusicUrlHandler,
		newKwServiceKwMusicUrlArgs,
		newKwServiceKwMusicUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	kwServiceServiceInfo                = NewServiceInfo()
	kwServiceServiceInfoForClient       = NewServiceInfoForClient()
	kwServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return kwServiceServiceInfo
}

// for stream start
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return kwServiceServiceInfoForStreamClient
}

// for start
func serviceInfoForClient() *kitex.ServiceInfo {
	return kwServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KwService"
	handlerType := (*kw.KwService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kw",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.0",
		Extra:           extra,
	}
	return svcInfo
}

func kwMusicUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kw.KwServiceKwMusicUrlArgs)
	realResult := result.(*kw.KwServiceKwMusicUrlResult)
	success, err := handler.(kw.KwService).KwMusicUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKwServiceKwMusicUrlArgs() interface{} {
	return kw.NewKwServiceKwMusicUrlArgs()
}

func newKwServiceKwMusicUrlResult() interface{} {
	return kw.NewKwServiceKwMusicUrlResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) KwMusicUrl(ctx context.Context, req *kw.KwRequest) (r *kw.KwResponse, err error) {
	var _args kw.KwServiceKwMusicUrlArgs
	_args.Req = req
	var _result kw.KwServiceKwMusicUrlResult
	if err = p.c.Call(ctx, "KwMusicUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
