// Code generated by Kitex v0.13.0. DO NOT EDIT.

package mgservice

import (
	"context"
	"errors"
	mg "github.com/ChangKaiChen/lx-music-api-server/kitex_gen/mg"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"MgMusicUrl": kitex.NewMethodInfo(
		mgMusicUrlHandler,
		newMgServiceMgMusicUrlArgs,
		newMgServiceMgMusicUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	mgServiceServiceInfo                = NewServiceInfo()
	mgServiceServiceInfoForClient       = NewServiceInfoForClient()
	mgServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return mgServiceServiceInfo
}

// for stream start
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return mgServiceServiceInfoForStreamClient
}

// for start
func serviceInfoForClient() *kitex.ServiceInfo {
	return mgServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MgService"
	handlerType := (*mg.MgService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "mg",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.0",
		Extra:           extra,
	}
	return svcInfo
}

func mgMusicUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mg.MgServiceMgMusicUrlArgs)
	realResult := result.(*mg.MgServiceMgMusicUrlResult)
	success, err := handler.(mg.MgService).MgMusicUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMgServiceMgMusicUrlArgs() interface{} {
	return mg.NewMgServiceMgMusicUrlArgs()
}

func newMgServiceMgMusicUrlResult() interface{} {
	return mg.NewMgServiceMgMusicUrlResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MgMusicUrl(ctx context.Context, req *mg.MgRequest) (r *mg.MgResponse, err error) {
	var _args mg.MgServiceMgMusicUrlArgs
	_args.Req = req
	var _result mg.MgServiceMgMusicUrlResult
	if err = p.c.Call(ctx, "MgMusicUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
