// Code generated by Kitex v0.13.0. DO NOT EDIT.

package wyservice

import (
	"context"
	"errors"
	wy "github.com/ChangKaiChen/lx-music-api-server/kitex_gen/wy"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"WyMusicUrl": kitex.NewMethodInfo(
		wyMusicUrlHandler,
		newWyServiceWyMusicUrlArgs,
		newWyServiceWyMusicUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	wyServiceServiceInfo                = NewServiceInfo()
	wyServiceServiceInfoForClient       = NewServiceInfoForClient()
	wyServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return wyServiceServiceInfo
}

// for stream start
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return wyServiceServiceInfoForStreamClient
}

// for start
func serviceInfoForClient() *kitex.ServiceInfo {
	return wyServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WyService"
	handlerType := (*wy.WyService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "wy",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.0",
		Extra:           extra,
	}
	return svcInfo
}

func wyMusicUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*wy.WyServiceWyMusicUrlArgs)
	realResult := result.(*wy.WyServiceWyMusicUrlResult)
	success, err := handler.(wy.WyService).WyMusicUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWyServiceWyMusicUrlArgs() interface{} {
	return wy.NewWyServiceWyMusicUrlArgs()
}

func newWyServiceWyMusicUrlResult() interface{} {
	return wy.NewWyServiceWyMusicUrlResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) WyMusicUrl(ctx context.Context, req *wy.WyRequest) (r *wy.WyResponse, err error) {
	var _args wy.WyServiceWyMusicUrlArgs
	_args.Req = req
	var _result wy.WyServiceWyMusicUrlResult
	if err = p.c.Call(ctx, "WyMusicUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
