// Code generated by Kitex v0.13.0. DO NOT EDIT.

package txservice

import (
	"context"
	"errors"
	tx "github.com/ChangKaiChen/lx-music-api-server/kitex_gen/tx"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"TxMusicUrl": kitex.NewMethodInfo(
		txMusicUrlHandler,
		newTxServiceTxMusicUrlArgs,
		newTxServiceTxMusicUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	txServiceServiceInfo                = NewServiceInfo()
	txServiceServiceInfoForClient       = NewServiceInfoForClient()
	txServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return txServiceServiceInfo
}

// for stream start
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return txServiceServiceInfoForStreamClient
}

// for start
func serviceInfoForClient() *kitex.ServiceInfo {
	return txServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TxService"
	handlerType := (*tx.TxService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "tx",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.0",
		Extra:           extra,
	}
	return svcInfo
}

func txMusicUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*tx.TxServiceTxMusicUrlArgs)
	realResult := result.(*tx.TxServiceTxMusicUrlResult)
	success, err := handler.(tx.TxService).TxMusicUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTxServiceTxMusicUrlArgs() interface{} {
	return tx.NewTxServiceTxMusicUrlArgs()
}

func newTxServiceTxMusicUrlResult() interface{} {
	return tx.NewTxServiceTxMusicUrlResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TxMusicUrl(ctx context.Context, req *tx.TxRequest) (r *tx.TxResponse, err error) {
	var _args tx.TxServiceTxMusicUrlArgs
	_args.Req = req
	var _result tx.TxServiceTxMusicUrlResult
	if err = p.c.Call(ctx, "TxMusicUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
