// Code generated by Kitex v0.13.0. DO NOT EDIT.

package scriptservice

import (
	"context"
	"errors"
	script "github.com/ChangKaiChen/lx-music-api-server/kitex_gen/script"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Script": kitex.NewMethodInfo(
		scriptHandler,
		newScriptServiceScriptArgs,
		newScriptServiceScriptResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	scriptServiceServiceInfo                = NewServiceInfo()
	scriptServiceServiceInfoForClient       = NewServiceInfoForClient()
	scriptServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return scriptServiceServiceInfo
}

// for stream start
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return scriptServiceServiceInfoForStreamClient
}

// for start
func serviceInfoForClient() *kitex.ServiceInfo {
	return scriptServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ScriptService"
	handlerType := (*script.ScriptService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "script",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.0",
		Extra:           extra,
	}
	return svcInfo
}

func scriptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*script.ScriptServiceScriptArgs)
	realResult := result.(*script.ScriptServiceScriptResult)
	success, err := handler.(script.ScriptService).Script(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newScriptServiceScriptArgs() interface{} {
	return script.NewScriptServiceScriptArgs()
}

func newScriptServiceScriptResult() interface{} {
	return script.NewScriptServiceScriptResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Script(ctx context.Context, req *script.ScriptRequest) (r *script.ScriptResponse, err error) {
	var _args script.ScriptServiceScriptArgs
	_args.Req = req
	var _result script.ScriptServiceScriptResult
	if err = p.c.Call(ctx, "Script", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
