// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package mg

import (
	"context"
	"fmt"
)

type MgRequest struct {
	SongId  string `thrift:"songId,1,required" frugal:"1,required,string" json:"songId"`
	Quality string `thrift:"quality,2,required" frugal:"2,required,string" json:"quality"`
}

func NewMgRequest() *MgRequest {
	return &MgRequest{}
}

func (p *MgRequest) InitDefault() {
}

func (p *MgRequest) GetSongId() (v string) {
	return p.SongId
}

func (p *MgRequest) GetQuality() (v string) {
	return p.Quality
}
func (p *MgRequest) SetSongId(val string) {
	p.SongId = val
}
func (p *MgRequest) SetQuality(val string) {
	p.Quality = val
}

func (p *MgRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MgRequest(%+v)", *p)
}

var fieldIDToName_MgRequest = map[int16]string{
	1: "songId",
	2: "quality",
}

type MgResponse struct {
	Code  int16  `thrift:"code,1,required" frugal:"1,required,i16" json:"code"`
	Msg   string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Data  string `thrift:"data,3" frugal:"3,default,string" json:"data"`
	Extra *Extra `thrift:"extra,4" frugal:"4,default,Extra" json:"extra"`
}

func NewMgResponse() *MgResponse {
	return &MgResponse{}
}

func (p *MgResponse) InitDefault() {
}

func (p *MgResponse) GetCode() (v int16) {
	return p.Code
}

func (p *MgResponse) GetMsg() (v string) {
	return p.Msg
}

func (p *MgResponse) GetData() (v string) {
	return p.Data
}

var MgResponse_Extra_DEFAULT *Extra

func (p *MgResponse) GetExtra() (v *Extra) {
	if !p.IsSetExtra() {
		return MgResponse_Extra_DEFAULT
	}
	return p.Extra
}
func (p *MgResponse) SetCode(val int16) {
	p.Code = val
}
func (p *MgResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *MgResponse) SetData(val string) {
	p.Data = val
}
func (p *MgResponse) SetExtra(val *Extra) {
	p.Extra = val
}

func (p *MgResponse) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *MgResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MgResponse(%+v)", *p)
}

var fieldIDToName_MgResponse = map[int16]string{
	1: "code",
	2: "msg",
	3: "data",
	4: "extra",
}

type Extra struct {
	Cache   bool     `thrift:"cache,1,required" frugal:"1,required,bool" json:"cache"`
	Quality *Quality `thrift:"quality,2,required" frugal:"2,required,Quality" json:"quality"`
	Expire  *Expire  `thrift:"expire,3,required" frugal:"3,required,Expire" json:"expire"`
}

func NewExtra() *Extra {
	return &Extra{}
}

func (p *Extra) InitDefault() {
}

func (p *Extra) GetCache() (v bool) {
	return p.Cache
}

var Extra_Quality_DEFAULT *Quality

func (p *Extra) GetQuality() (v *Quality) {
	if !p.IsSetQuality() {
		return Extra_Quality_DEFAULT
	}
	return p.Quality
}

var Extra_Expire_DEFAULT *Expire

func (p *Extra) GetExpire() (v *Expire) {
	if !p.IsSetExpire() {
		return Extra_Expire_DEFAULT
	}
	return p.Expire
}
func (p *Extra) SetCache(val bool) {
	p.Cache = val
}
func (p *Extra) SetQuality(val *Quality) {
	p.Quality = val
}
func (p *Extra) SetExpire(val *Expire) {
	p.Expire = val
}

func (p *Extra) IsSetQuality() bool {
	return p.Quality != nil
}

func (p *Extra) IsSetExpire() bool {
	return p.Expire != nil
}

func (p *Extra) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Extra(%+v)", *p)
}

var fieldIDToName_Extra = map[int16]string{
	1: "cache",
	2: "quality",
	3: "expire",
}

type Quality struct {
	Target  string `thrift:"target,1,required" frugal:"1,required,string" json:"target"`
	Result_ string `thrift:"result,2,required" frugal:"2,required,string" json:"result"`
}

func NewQuality() *Quality {
	return &Quality{}
}

func (p *Quality) InitDefault() {
}

func (p *Quality) GetTarget() (v string) {
	return p.Target
}

func (p *Quality) GetResult_() (v string) {
	return p.Result_
}
func (p *Quality) SetTarget(val string) {
	p.Target = val
}
func (p *Quality) SetResult_(val string) {
	p.Result_ = val
}

func (p *Quality) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Quality(%+v)", *p)
}

var fieldIDToName_Quality = map[int16]string{
	1: "target",
	2: "result",
}

type Expire struct {
	Time      int64 `thrift:"time,1,required" frugal:"1,required,i64" json:"time"`
	CanExpire bool  `thrift:"canExpire,2,required" frugal:"2,required,bool" json:"canExpire"`
}

func NewExpire() *Expire {
	return &Expire{}
}

func (p *Expire) InitDefault() {
}

func (p *Expire) GetTime() (v int64) {
	return p.Time
}

func (p *Expire) GetCanExpire() (v bool) {
	return p.CanExpire
}
func (p *Expire) SetTime(val int64) {
	p.Time = val
}
func (p *Expire) SetCanExpire(val bool) {
	p.CanExpire = val
}

func (p *Expire) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Expire(%+v)", *p)
}

var fieldIDToName_Expire = map[int16]string{
	1: "time",
	2: "canExpire",
}

type MgService interface {
	MgMusicUrl(ctx context.Context, req *MgRequest) (r *MgResponse, err error)
}

type MgServiceMgMusicUrlArgs struct {
	Req *MgRequest `thrift:"req,1" frugal:"1,default,MgRequest" json:"req"`
}

func NewMgServiceMgMusicUrlArgs() *MgServiceMgMusicUrlArgs {
	return &MgServiceMgMusicUrlArgs{}
}

func (p *MgServiceMgMusicUrlArgs) InitDefault() {
}

var MgServiceMgMusicUrlArgs_Req_DEFAULT *MgRequest

func (p *MgServiceMgMusicUrlArgs) GetReq() (v *MgRequest) {
	if !p.IsSetReq() {
		return MgServiceMgMusicUrlArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MgServiceMgMusicUrlArgs) SetReq(val *MgRequest) {
	p.Req = val
}

func (p *MgServiceMgMusicUrlArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MgServiceMgMusicUrlArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MgServiceMgMusicUrlArgs(%+v)", *p)
}

var fieldIDToName_MgServiceMgMusicUrlArgs = map[int16]string{
	1: "req",
}

type MgServiceMgMusicUrlResult struct {
	Success *MgResponse `thrift:"success,0,optional" frugal:"0,optional,MgResponse" json:"success,omitempty"`
}

func NewMgServiceMgMusicUrlResult() *MgServiceMgMusicUrlResult {
	return &MgServiceMgMusicUrlResult{}
}

func (p *MgServiceMgMusicUrlResult) InitDefault() {
}

var MgServiceMgMusicUrlResult_Success_DEFAULT *MgResponse

func (p *MgServiceMgMusicUrlResult) GetSuccess() (v *MgResponse) {
	if !p.IsSetSuccess() {
		return MgServiceMgMusicUrlResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MgServiceMgMusicUrlResult) SetSuccess(x interface{}) {
	p.Success = x.(*MgResponse)
}

func (p *MgServiceMgMusicUrlResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MgServiceMgMusicUrlResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MgServiceMgMusicUrlResult(%+v)", *p)
}

var fieldIDToName_MgServiceMgMusicUrlResult = map[int16]string{
	0: "success",
}
